services:
  - type: web
    name: lotto-ai
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180 --workers 1 --threads 1 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: RENDER
        value: true
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PROXY_SERVER
        value: ""
      - key: PROXY_USER
        value: ""
      - key: PROXY_PASS
        value: ""
